# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:24:32+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    HscerCertificatePostRequest,
    HscerCertificatePostResponse,
    HscerCertificatePostResponse1,
    HscerCertificatePostResponse2,
    HscerCertificatePostResponse3,
    HscerCertificatePostResponse4,
    HscerCertificatePostResponse5,
    HscerCertificatePostResponse6,
)

app = MCPProxy(
    description='Tripura Board of Secondary Education, (http://tbse.in) has made available Class X (2017-2019) Marksheets in DigiLocker, which can be pulled by students into their accounts.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Tripura State Board of Secondary Education, Tripura',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/tbse/v3'}],
)


@app.post(
    '/hscer/certificate',
    description=""" API to verify Class XII Marksheet. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def hscer(body: HscerCertificatePostRequest = None):
    """
    Class XII Marksheet
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
